name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - run: echo "🧪 Testing..."
  
