name: GitHub Actions Demo
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - run: echo "🧪 Testing..."
  
